apiVersion: v1
kind: Namespace
metadata:
  name: kartol-staging
  labels:
    name: kartol-staging
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: kartol-production
  labels:
    name: kartol-production
    environment: production
