apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kartol-app-staging-ingress
  namespace: kartol-staging
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-staging
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
spec:
  tls:
  - hosts:
    - staging.kartol.com
    secretName: kartol-staging-tls
  rules:
  - host: staging.kartol.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kartol-app-staging-service
            port:
              number: 80
